slack:
  webhook_url: "${SLACK_WEBHOOK_URL}" # Set this environment variable
  
monitoring:
  interval: "5s" # How often to check
  timeout: "10s"  # Timeout for each call
  
kyberswap:
  api_base_url: "https://aggregator-api.kyberswap.com"
  client_id: "scale-helper-test"
  
chains:
  - name: "ethereum"
    chain_id: 1
    rpc_url: "${ETH_NODE_URL}" # Set this environment variable
    contract_address: "${ETH_CONTRACT_ADDRESS}" # Set this environment variable
    
  - name: "polygon"
    chain_id: 137
    rpc_url: "${POLYGON_NODE_URL}" # Set this environment variable  
    contract_address: "${POLYGON_CONTRACT_ADDRESS}" # Set this environment variable
    
  - name: "bsc"
    chain_id: 56
    rpc_url: "${BSC_NODE_URL}" # Set this environment variable
    contract_address: "${BSC_CONTRACT_ADDRESS}" # Set this environment variable
    
  - name: "arbitrum"
    chain_id: 42161
    rpc_url: "${ARBITRUM_NODE_URL}" # Set this environment variable
    contract_address: "${ARBITRUM_CONTRACT_ADDRESS}" # Set this environment variable

test_tokens:
  # Test token pairs for monitoring
  - chain_name: "polygon"
    token_in: "0x7ceb23fd6bc0add59e62ac25578270cff1b9f619" # WETH
    token_out: "0x2791bca1f2de4661ed88a30c99a7a9449aa84174" # USDC
    amount: "1000000000000000000" # 100 WETH
    
  - chain_name: "ethereum"
    token_in: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2" # WETH
    token_out: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48" # USDC
    amount: "1000000000000000000" # 1 WETH 

  - chain_name: "bsc" 
    token_in: "0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c" # WBNB
    token_out: "0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d" # USDC
    amount: "1000000000000000000" # 1 WBNB

  - chain_name: "arbitrum"
    token_in: "0x82af49447d8a07e3bd95bd0d56f35241523fbab1" # WETH
    token_out: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831" # USDC
    amount: "1000000000000000000" # 1 WETH